services:
  galaxy-archive-fe:
    image: ghcr.io/${REPO_LOWER}/galaxy-archive-fe:latest
    container_name: galaxy-archive-fe
    restart: always
    env_file:
      - .front.env
    environment:
      - INTERNAL_API_URL=${INTERNAL_API_URL}
      - NEXT_PUBLIC_IMAGE_BASE_URL=${NEXT_PUBLIC_IMAGE_BASE_URL}
    networks:
      - galaxy-network

networks:
  galaxy-network:
    external: true