services:
  galaxy-archive-fe:
    image: ghcr.io/${REPO_LOWER}/galaxy-archive-fe:latest
    container_name: galaxy-archive-fe
    restart: always
    ports:
      - "3000:3000"
    networks:
      - galaxy-network

networks:
  galaxy-network:
    external: true