import type { Metadata } from "next";
import "./globals.css";
import {ThemeProvider} from "next-themes";
import {Header} from "@/components/header/Header";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="kr" suppressHydrationWarning>

      <body>

        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange={false}
        >
        <Header/>
            {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
